#  Required Variables set by external Pipeline Configuration
#
#  buildConfiguration:             Build Configuration Type, for example 'Release'
#  Build.ArtifactStagingDirectory: Directory to stage artifact assembly.

steps:

- task: DotNetCoreInstaller@0
  displayName: 'Ensure .Net Core 6.0'  
  inputs:
    version: '6.0.101'

- task: DotNetCoreCLI@2
  displayName: Restore Dependencies  
  inputs:
    command: restore
    projects: Hashgraph.Portal/Hashgraph.Portal.csproj

- task: DotNetCoreCLI@2
  displayName: Build Projects  
  inputs:
    command: build
    projects: Hashgraph.Portal/Hashgraph.Portal.csproj
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish Projects
  inputs:
    command: publish
    projects: Hashgraph.Portal/Hashgraph.Portal.csproj
    publishWebProjects: True
    arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: True

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    pathtoPublish: '$(build.artifactstagingdirectory)'
    artifactName: 'hashgaph-portal-package-$(Build.BuildNumber)'
